name: Build WebDocument

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    #- name: Setup docfx
    #  run: choco install docfx --version=2.45.1

    - name: Build
      uses: nikeee/docfx-action@master
      with:
        args: docs/WebDocument/docfx.json
    #  run: |
    #    cd docs/WebDocument
    #    docfx build

    - name: Deploy
      env:
        CI_PUSH_TOKEN: ${{ secrets.CI_PUSH_TOKEN }}
      run: |
        cd docs/WebDocument
        git clone https://${GITHUB_ACTOR}:${CI_PUSH_TOKEN}@github.com/lriki/lriki.github.io _docs_repo
        cp -rf _site _docs_repo/latest-lumino-webdocs
        cd _docs_repo
        ls 
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config core.autoCRLF false
        git add .
        git commit -m '[CI] Deploy to GitHub Pages'
        git status
        #git config --list
        echo "git push"
        git push origin master
        echo $lastexitcode

